name: hisnrlab
services:
  server:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: docker:image_v1
    container_name: hisnr_website
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
      - "35729:35729"
    command: bundle exec jekyll serve --host 0.0.0.0 --livereload