name: on-pages
run-name: on pages deploy

on:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed
    branches:
      - main

  # Allows you to run this manually from the Actions tab
  workflow_dispatch:

# Grant the permission scopes required for GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-site:
    # We removed the broken 'if: needs.update-url...' line so it runs cleanly
    uses: HI-SNR-Lab/HI-SNR.github.io/.github/workflows/build-site.yaml@main
